server:
  port: 8080


eureka:
  instance:
    hostname: localhost # 主机名
    prefer-ip-address: true # 是否将自己的ip注册到eureka中，默认false 注册 主机名
    ip-address: localhost # 设置当前实例ip
#    instance-id: provider # 修改instance-id显示
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 3 # 每一次eureka client 向 eureka server发送心跳的时间间隔
    lease-expiration-duration-in-seconds: 9 # 如果90秒内eureka server没有收到eureka client的心跳包，则剔除该服务
  client:
    register-with-eureka: true # 是否将自己的路径 注册到eureka上。
    fetch-registry: true # 是否需要从eureka中抓取数据。
    service-url:
# 测试高可用时修改后的配置      defaultZone: http://eureka-server1:8201/eureka, http://eureka-server2:8202/eureka # eureka服务端地址，将来客户端使用该地址和eureka进行通信
      defaultZone: http://localhost:8300/eureka # eureka服务端地址，将来客户端使用该地址和eureka进行通信
spring:
  application:
    name: EUREKA-PROVIDER # 设置当前应用的名称。将来会在eureka中Application显示。将来需要使用该名称来获取路径

bld: ssa
